# Site settings
title: Nadjib's Profile
email: hello@ebabel.eu
description: > # this means to ignore newlines until "baseurl:"
  Making a dent in the universe (trying!)
baseurl: "/patchwork-gh-pages-24"
url: "http://ebabel-eu.github.io"
twitter_username: eBabel
github_username:  ebabel-eu
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
